### ISSUE TITLE
No Build Permission in Room

### ISSUE THREAD

**Issue by JaXxTeller** [gvlfm78/BukkitHotels#24]
Hello. really nice plugin. thank you for this great work. but we have a small problem. the tenants of rooms should be set up her room herself. bed, boxes, signs, ect ... unfortunately it does not work for us. how do I distribute the permissions? Or set the flags?

about an answer I would be very happy!

**Comment by gvlfm78** [comment]
You can change the flags in the flags.yml file and put the build flag to
true for the rooms. In hotels 1.0.0 I will be adding the ability for rooms
to be saved and reset once the rent is over.

Il 16/ago/2016 17:29, "JaXxTeller" <notifications@github.com> ha scritto:

**Comment by JaXxTeller** [comment]
These are the settings that I made for the room. but it does not work :(

room:
  overrides:
    PASSTHROUGH: none
    EXIT-OVERRIDE: none
  protection:
    BUILD: -g non_members deny
    INTERACT: -g non_members deny
    BLOCK-BREAK: none
    BLOCK-PLACE: none
    USE: -g non_members deny
    DAMAGE-ANIMALS: none
    CHEST-ACCESS: -g non_members deny
    RIDE: -g non_members deny
    PVP: deny
    SLEEP: -g non_members deny
    TNT: deny
    VEHICLE-PLACE: -g non_members deny
    VEHICLE-DESTROY: -g non_members deny
    LIGHTER: deny

**Comment by gvlfm78** [comment]
Put a -g non_members deny also in the block-place and block-break. Also
remember that the flags are only reapplied to the rooms if any of the allow
players to enter free rooms or allow players to open containers in free
rooms is enabled, otherwise you will have to recreate the room.

Il 16/ago/2016 17:49, "JaXxTeller" <notifications@github.com> ha scritto:

**Comment by JaXxTeller** [comment]
now running <3 

//close
