### ISSUE TITLE
Pistons does not extend when powered

### ISSUE THREAD

**Issue by eirikh1996** [gvlfm78/BukkitHotels#3]
Within the hotel, pistons does not extend, even when it is powered. I used the pistons to create sliding doors on an EasyElevator based elevator within the hotel area and using the elevators redstone output to power the doors that should open when platform is at the designated floor, however, they do retract, but doesnt extend, causing the doors to remain open when the platform leaves that floor.

**Comment by gvlfm78** [comment]
What is blocking your pistons from working there is a WorldGuard flag applied by default by Hotels to the hotel region. This isn't really a bug since some people will want pistons to be blocked and others wont. In a future realease I will probably change the code to leave the flag null so the pistons will work anyway. To fix your issue you would either have to re-create the whole hotel with a new release (which hasn't come out yet) or just do */rg f hotel-name pistons none* to set the flag back to default or */rg f hotel-name pistons allow* to set the flag to override any other region there.
