### ISSUE TITLE
Fixed mistakes in Russian language

### ISSUE THREAD

**Issue by SPYmeYT** [gvlfm78/BukkitHotels#32]
[locale.zip](https://github.com/gvlfm78/BukkitHotels/files/943299/locale.zip)
I'm on spigot: @SPY_me

Tnx for this great plugin!

**Comment by gvlfm78** [comment]
Thank you! I have just updated the Russian translations with yours on the [Hotels Translation Project](https://poeditor.com/join/project/JZCEZoYecm) site. In the future it might be better if you do them directly there, but for this time it's fine, because I could just convert the file and upload it.
