### ISSUE TITLE
Players cant get in creationmode

### ISSUE THREAD

**Issue by JakobFrand** [gvlfm78/BukkitHotels#44]
My players cant get i creations mode even though they have both hotels.create.user and hotels.createmode.user 

I can do it but i also have the * permission so the plugin works just not the permissions

**Comment by gvlfm78** [comment]
Please follow these steps and check in-between each step if the problem is still present:

1. Try revoking those permissions and seeing if there is a change.
2. Give those permissions back and check if the problem is still present
3. Also give them **hotels.sign.create.user**
4. Also give them **worldedit.selection.pos**

**Comment by JakobFrand** [comment]
Ive still got the problem i have followed all your steps but it still dont work 
Then ive tried to get them the hotels.* and then it works so the plugin works and all the other permissions than the hotels creations mode

**Comment by gvlfm78** [comment]
Hmm I think I have changed that permission to **hotels.creationmode** but never updated the wiki

**Comment by JakobFrand** [comment]
Cool it works now thanks!!
