### ISSUE TITLE
Dont Work With New Version Of MineCraft 1.8.6

### ISSUE THREAD

**Issue by Kazina** [gvlfm78/BukkitHotels#6]
Don't Seem to work at all /hotels and so on not even showing up

**Comment by gvlfm78** [comment]
The latest version of Hotels is compiled for 1.8.5, and it works on such version. I will have any newer update compiled on newer versions, for now you might want to keep the 1.8.5 server version although there shouldn't be much difference cross-version and so it doesn't make much sense for the plugin to not work at all. Are you sure the problem lies in the Bukkit/Spigot version and not somewhere else?

**Comment by gvlfm78** [comment]
The new version of Hotels will be compiled for the newest version of Bukkit available at the moement - right now that would be 1.8.7

**Comment by Kazina** [comment]
thank you for the info
